package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"strings"
)

const (
	adminPasswordLength = 32
	apiKeyHexLength     = 32 // 32 hex chars = 16 bytes
	apiKeyPrefix        = "sk-ccproxy-"
	passwordCharset     = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
)

// GenerateAdminPassword returns a cryptographically random 32-character
// password using uppercase, lowercase letters and digits.
func GenerateAdminPassword() string {
	b := make([]byte, adminPasswordLength)
	if _, err := rand.Read(b); err != nil {
		panic(fmt.Sprintf("crypto/rand failed: %v", err))
	}
	for i := range b {
		b[i] = passwordCharset[int(b[i])%len(passwordCharset)]
	}
	return string(b)
}

// GenerateAPIKey returns a key in the format "sk-ccproxy-<32 hex chars>".
func GenerateAPIKey() string {
	b := make([]byte, apiKeyHexLength/2)
	if _, err := rand.Read(b); err != nil {
		panic(fmt.Sprintf("crypto/rand failed: %v", err))
	}
	return apiKeyPrefix + hex.EncodeToString(b)
}

// autoGenerate fills in missing admin_password and api_keys, writes them
// to the config file, and returns which credentials were generated.
func autoGenerate(cfg *Config, path string) (generatedPassword, generatedKey bool) {

	if cfg.Server.AdminPassword == "" {
		cfg.Server.AdminPassword = GenerateAdminPassword()
		generatedPassword = true
	}

	enabledKeys := 0
	for _, k := range cfg.APIKeys {
		if k.Enabled {
			enabledKeys++
		}
	}
	if enabledKeys == 0 {
		cfg.APIKeys = append(cfg.APIKeys, APIKeyConfig{
			Key:     GenerateAPIKey(),
			Name:    "default",
			Enabled: true,
		})
		generatedKey = true
	}

	if !generatedPassword && !generatedKey {
		return false, false
	}

	// Persist generated values to config file
	if err := writeGeneratedToFile(path, cfg, generatedPassword, generatedKey); err != nil {
		slog.Warn("failed to save generated credentials, will be lost on restart", "path", path, "error", err.Error())
	} else {
		slog.Info("credentials auto-generated and saved", "path", path, "generated_password", generatedPassword, "generated_key", generatedKey)
	}

	return generatedPassword, generatedKey
}

// writeGeneratedToFile appends or replaces generated values in the config file,
// preserving existing content and comments.
func writeGeneratedToFile(path string, cfg *Config, password, apiKey bool) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read config file: %w", err)
	}
	content := string(data)

	if password {
		content = insertAdminPassword(content, cfg.Server.AdminPassword)
	}

	if apiKey {
		// Find the generated key (the last one appended)
		k := cfg.APIKeys[len(cfg.APIKeys)-1]
		content = appendAPIKey(content, k)
	}

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write config file: %w", err)
	}
	return nil
}

// insertAdminPassword replaces an empty admin_password line or appends one
// after the [server] section header.
func insertAdminPassword(content, password string) string {
	escaped := fmt.Sprintf("admin_password = %q", password)

	// Try replacing existing empty admin_password line
	lines := strings.Split(content, "\n")
	replaced := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "admin_password") && strings.Contains(trimmed, "=") {
			// Check if the value is empty (e.g. admin_password = "" or admin_password = '')
			parts := strings.SplitN(trimmed, "=", 2)
			val := strings.TrimSpace(parts[1])
			if val == `""` || val == "''" || val == "" {
				lines[i] = escaped + "  # auto-generated by ccproxy"
				replaced = true
				break
			}
		}
	}

	if replaced {
		return strings.Join(lines, "\n")
	}

	// Find [server] section and insert after it
	for i, line := range lines {
		if strings.TrimSpace(line) == "[server]" {
			// Insert after [server] line
			newLines := make([]string, 0, len(lines)+1)
			newLines = append(newLines, lines[:i+1]...)
			newLines = append(newLines, escaped+"  # auto-generated by ccproxy")
			newLines = append(newLines, lines[i+1:]...)
			return strings.Join(newLines, "\n")
		}
	}

	// No [server] section at all — prepend one
	return fmt.Sprintf("[server]\n%s  # auto-generated by ccproxy\n\n%s", escaped, content)
}

// appendAPIKey adds a [[api_keys]] block at the end of the content.
func appendAPIKey(content string, k APIKeyConfig) string {
	block := fmt.Sprintf(
		"\n# Auto-generated by ccproxy\n[[api_keys]]\nkey = %q\nname = %q\nenabled = true\n",
		k.Key, k.Name,
	)
	return strings.TrimRight(content, "\n") + "\n" + block
}

// printGeneratedCredentials outputs a visible banner with the generated values.
func printGeneratedCredentials(cfg *Config, generatedPassword, generatedKey bool) {
	fmt.Fprintln(os.Stderr, "================================================================")
	fmt.Fprintln(os.Stderr, "  Auto-generated credentials (saved to config file):")
	fmt.Fprintln(os.Stderr)
	if generatedPassword {
		fmt.Fprintf(os.Stderr, "  Admin Password: %s\n", cfg.Server.AdminPassword)
	}
	if generatedKey {
		k := cfg.APIKeys[len(cfg.APIKeys)-1]
		fmt.Fprintf(os.Stderr, "  API Key:        %s (name: %s)\n", k.Key, k.Name)
	}
	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "  Please save these credentials securely.")
	fmt.Fprintln(os.Stderr, "================================================================")
}
