package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"strings"

	"github.com/binn/ccproxy/internal/fileutil"
)

const (
	adminPasswordLength = 32
	apiKeyHexLength     = 64 // 64 hex chars = 32 bytes
	apiKeyPrefix        = "sk-"
	passwordCharset     = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
)

// GenerateAdminPassword returns a cryptographically random 32-character
// password using uppercase, lowercase letters and digits.
func GenerateAdminPassword() string {
	// Rejection sampling to eliminate modulo bias.
	// 256 % 62 = 8, so naive modulo has ~3.2% bias.
	const maxUnbiased = 256 - (256 % len(passwordCharset)) // 248
	b := make([]byte, adminPasswordLength)
	buf := make([]byte, 1)
	for i := range b {
		for {
			if _, err := rand.Read(buf); err != nil {
				panic("crypto/rand failed: " + err.Error())
			}
			if int(buf[0]) < maxUnbiased {
				b[i] = passwordCharset[int(buf[0])%len(passwordCharset)]
				break
			}
		}
	}
	return string(b)
}

// GenerateAPIKey returns a key in the format "sk-<64 hex chars>".
func GenerateAPIKey() string {
	b := make([]byte, apiKeyHexLength/2)
	if _, err := rand.Read(b); err != nil {
		panic(fmt.Sprintf("crypto/rand failed: %v", err))
	}
	return apiKeyPrefix + hex.EncodeToString(b)
}

// defaultUserNames are the names for auto-generated API key users.
var defaultUserNames = []string{"alice", "bob", "charlie"}

// autoGenerate fills in missing admin_password and api_keys, writes them
// to the config file, and returns which credentials were generated.
func autoGenerate(cfg *Config, path string) (generatedPassword, generatedKeys bool, generatedPasswords []int) {

	if cfg.Server.AdminPassword == "" {
		cfg.Server.AdminPassword = GenerateAdminPassword()
		generatedPassword = true
	}

	enabledKeys := 0
	for _, k := range cfg.APIKeys {
		if k.Enabled {
			enabledKeys++
		}
	}
	if enabledKeys == 0 {
		for _, name := range defaultUserNames {
			cfg.APIKeys = append(cfg.APIKeys, APIKeyConfig{
				Key:      GenerateAPIKey(),
				Name:     name,
				Password: GenerateAdminPassword(),
				Enabled:  true,
			})
		}
		generatedKeys = true
	}

	// Generate passwords for existing keys that don't have one.
	for i := range cfg.APIKeys {
		if cfg.APIKeys[i].Password == "" {
			cfg.APIKeys[i].Password = GenerateAdminPassword()
			generatedPasswords = append(generatedPasswords, i)
		}
	}

	needWrite := generatedPassword || generatedKeys || len(generatedPasswords) > 0
	if !needWrite {
		return generatedPassword, generatedKeys, nil
	}

	// Persist generated values to config file
	if err := writeGeneratedToFile(path, cfg, generatedPassword, generatedKeys, generatedPasswords); err != nil {
		slog.Warn("failed to save generated credentials, will be lost on restart", "path", path, "error", err.Error())
	} else {
		slog.Info("credentials auto-generated and saved", "path", path, "generated_password", generatedPassword, "generated_keys", generatedKeys, "generated_passwords", len(generatedPasswords))
	}

	return generatedPassword, generatedKeys, generatedPasswords
}

// writeGeneratedToFile appends or replaces generated values in the config file,
// preserving existing content and comments.
func writeGeneratedToFile(path string, cfg *Config, password, apiKeys bool, passwordIndices []int) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read config file: %w", err)
	}
	content := string(data)

	if password {
		content = insertAdminPassword(content, cfg.Server.AdminPassword)
	}

	if apiKeys {
		// Append all newly generated keys
		for _, k := range cfg.APIKeys {
			content = appendAPIKey(content, k)
		}
	}

	// Insert passwords into existing [[api_keys]] blocks that were missing them.
	if len(passwordIndices) > 0 && !apiKeys {
		content = insertAPIKeyPasswords(content, cfg, passwordIndices)
	}

	if err := fileutil.AtomicWriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write config file: %w", err)
	}
	return nil
}

// insertAdminPassword replaces an empty admin_password line or appends one
// after the [server] section header.
func insertAdminPassword(content, password string) string {
	escaped := fmt.Sprintf("admin_password = %q", password)

	// Try replacing existing empty admin_password line
	lines := strings.Split(content, "\n")
	replaced := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue // skip comments
		}
		if strings.HasPrefix(trimmed, "admin_password") && strings.Contains(trimmed, "=") {
			// Check if the value is empty (e.g. admin_password = "" or admin_password = '')
			parts := strings.SplitN(trimmed, "=", 2)
			val := strings.TrimSpace(parts[1])
			if val == `""` || val == "''" || val == "" {
				lines[i] = escaped + "  # auto-generated by ccproxy"
				replaced = true
				break
			}
		}
	}

	if replaced {
		return strings.Join(lines, "\n")
	}

	// Find [server] section and insert after it
	for i, line := range lines {
		if strings.TrimSpace(line) == "[server]" {
			// Insert after [server] line
			newLines := make([]string, 0, len(lines)+1)
			newLines = append(newLines, lines[:i+1]...)
			newLines = append(newLines, escaped+"  # auto-generated by ccproxy")
			newLines = append(newLines, lines[i+1:]...)
			return strings.Join(newLines, "\n")
		}
	}

	// No [server] section at all — prepend one
	return fmt.Sprintf("[server]\n%s  # auto-generated by ccproxy\n\n%s", escaped, content)
}

// appendAPIKey adds a [[api_keys]] block at the end of the content.
func appendAPIKey(content string, k APIKeyConfig) string {
	block := fmt.Sprintf(
		"\n# Auto-generated by ccproxy\n[[api_keys]]\nkey = %q\nname = %q\npassword = %q\nenabled = true\n",
		k.Key, k.Name, k.Password,
	)
	return strings.TrimRight(content, "\n") + "\n" + block
}

// insertAPIKeyPasswords inserts password lines into existing [[api_keys]] blocks
// for the keys at the given indices (those that had empty passwords).
func insertAPIKeyPasswords(content string, cfg *Config, indices []int) string {
	// Build a set of names that need password insertion.
	needPassword := make(map[string]string, len(indices))
	for _, idx := range indices {
		needPassword[cfg.APIKeys[idx].Name] = cfg.APIKeys[idx].Password
	}

	lines := strings.Split(content, "\n")
	var result []string
	var currentName string

	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])
		result = append(result, lines[i])

		// Track which [[api_keys]] block we're in by looking for name = "..."
		if strings.HasPrefix(trimmed, "name") && strings.Contains(trimmed, "=") && !strings.HasPrefix(trimmed, "#") {
			parts := strings.SplitN(trimmed, "=", 2)
			val := strings.TrimSpace(parts[1])
			val = strings.Trim(val, `"'`)
			currentName = val

			// If this name needs a password, insert it after the name line.
			if pw, ok := needPassword[currentName]; ok {
				result = append(result, fmt.Sprintf("password = %q  # auto-generated by ccproxy", pw))
				delete(needPassword, currentName)
			}
		}
	}

	return strings.Join(result, "\n")
}

// printGeneratedCredentials outputs a visible banner with the generated values.
func printGeneratedCredentials(cfg *Config, generatedPassword, generatedKeys bool, generatedPasswords []int) {
	fmt.Fprintln(os.Stderr, "================================================================")
	fmt.Fprintln(os.Stderr, "  Auto-generated credentials (saved to config file):")
	fmt.Fprintln(os.Stderr)
	if generatedPassword {
		fmt.Fprintf(os.Stderr, "  Admin Password: %s\n", cfg.Server.AdminPassword)
	}
	if generatedKeys {
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, "  API Keys:")
		for _, k := range cfg.APIKeys {
			fmt.Fprintf(os.Stderr, "    [%s] Key: %s\n", k.Name, k.Key)
			fmt.Fprintf(os.Stderr, "    [%s] Dashboard Password: %s\n", k.Name, k.Password)
			fmt.Fprintln(os.Stderr)
		}
	} else if len(generatedPasswords) > 0 {
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, "  Generated dashboard passwords for existing API keys:")
		for _, idx := range generatedPasswords {
			k := cfg.APIKeys[idx]
			fmt.Fprintf(os.Stderr, "    [%s] Dashboard Password: %s\n", k.Name, k.Password)
		}
		fmt.Fprintln(os.Stderr)
	}
	fmt.Fprintln(os.Stderr, "  Please save these credentials securely.")
	fmt.Fprintln(os.Stderr, "================================================================")
}
