package disguise

import (
	"encoding/json"
	"testing"
)

// TestComputeBillingFingerprintReplica_KnownVectors pins the historical
// SHA256-based replica algorithm to byte-exact expected values. These vectors
// were generated by the documented algorithm:
//
//	SHA256("59cf53e54c78" + msg[4] + msg[7] + msg[20] + version)[:3]
//
// with out-of-range indices substituted with '0'. The replica is now used
// only by BillingHeaderObserver — it has no production effect on outbound traffic.
// These tests pin its behaviour so that observed "match" log entries from
// the observer remain comparable across builds.
func TestComputeBillingFingerprintReplica_KnownVectors(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name    string
		msg     string
		version string
		want    string
	}{
		// msg shorter than max index (20) → all three chars are '0'.
		{"empty message 2.1.88", "", "2.1.88", "758"},
		{"empty message 2.1.76", "", "2.1.76", "4dc"},
		{"short message 2.1.88", "hi", "2.1.88", "758"},
		// Long enough to cover all three indices (4=o, 7=w, 20=t).
		{"long message 2.1.88", "Hello, world! This is a test message.", "2.1.88", "e72"},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := computeBillingFingerprintReplica(tc.msg, tc.version)
			if got != tc.want {
				t.Errorf("computeBillingFingerprintReplica(%q, %q) = %q, want %q",
					tc.msg, tc.version, got, tc.want)
			}
		})
	}
}

func TestExtractFirstUserMessageText(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		body string
		want string
	}{
		{
			name: "string content",
			body: `{"messages":[{"role":"user","content":"hello there"}]}`,
			want: "hello there",
		},
		{
			name: "array with text block",
			body: `{"messages":[{"role":"user","content":[{"type":"text","text":"block text"}]}]}`,
			want: "block text",
		},
		{
			name: "array with non-text block first",
			body: `{"messages":[{"role":"user","content":[{"type":"image"},{"type":"text","text":"t"}]}]}`,
			want: "t",
		},
		{
			name: "assistant before user",
			body: `{"messages":[{"role":"assistant","content":"ai"},{"role":"user","content":"human"}]}`,
			want: "human",
		},
		{
			name: "no user message",
			body: `{"messages":[{"role":"assistant","content":"ai"}]}`,
			want: "",
		},
		{
			name: "no messages field",
			body: `{}`,
			want: "",
		},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			parsed := parseJSON(t, tc.body)
			got := extractFirstUserMessageText(parsed)
			if got != tc.want {
				t.Errorf("extractFirstUserMessageText = %q, want %q", got, tc.want)
			}
		})
	}
}

// TestSyncBillingHeaderVersion_RecomputesSuffix pins the central invariant
// of the cch-attestation rollout: rewriting the cc_version triple ALSO
// recomputes the .abc 3hex suffix using vM3 semantics over messages, AND
// resets the cch field to the "00000" placeholder so the post-marshal
// rewriter can write the real hash. The client's old suffix and cch are
// both invalid the moment we change the body.
func TestSyncBillingHeaderVersion_RecomputesSuffix(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.105.a29; cc_entrypoint=cli; cch=1931e;"}
		],
		"messages": [{"role":"user","content":"hello"}]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.97")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	// 3hex is recomputed with messages="hello" and version="2.1.97"
	wantSuffix := Compute3HexSuffix("2.1.97", []interface{}{
		map[string]interface{}{"role": "user", "content": "hello"},
	})
	want := "x-anthropic-billing-header: cc_version=2.1.97." + wantSuffix + "; cc_entrypoint=cli; cch=00000;"
	if got != want {
		t.Errorf("expected suffix recomputed and cch reset to placeholder\n  want %q\n  got  %q", want, got)
	}
}

// TestSyncBillingHeaderVersion_DowngradeStillRewrites verifies that the
// rewrite is unconditional with respect to version ordering: even if the
// fp UA version is OLDER than the client's cc_version, we still rewrite
// the triple AND recompute the suffix.
func TestSyncBillingHeaderVersion_DowngradeStillRewrites(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.2.0.abc; cc_entrypoint=cli;"}
		],
		"messages": [{"role":"user","content":"hi"}]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	wantSuffix := Compute3HexSuffix("2.1.88", []interface{}{
		map[string]interface{}{"role": "user", "content": "hi"},
	})
	want := "x-anthropic-billing-header: cc_version=2.1.88." + wantSuffix + "; cc_entrypoint=cli; cch=00000;"
	if got != want {
		t.Errorf("expected downgrade to 2.1.88 with recomputed suffix\n  want %q\n  got  %q", want, got)
	}
}

// TestSyncBillingHeaderVersion_NoSuffix_GetsSuffix verifies that when the
// client sent a suffix-less cc_version, we still synthesize one — the
// 3hex is mandatory in the new strategy.
func TestSyncBillingHeaderVersion_NoSuffix_GetsSuffix(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76; cc_entrypoint=cli;"}
		],
		"messages": [{"role":"user","content":"hi"}]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	wantSuffix := Compute3HexSuffix("2.1.88", []interface{}{
		map[string]interface{}{"role": "user", "content": "hi"},
	})
	want := "x-anthropic-billing-header: cc_version=2.1.88." + wantSuffix + "; cc_entrypoint=cli; cch=00000;"
	if got != want {
		t.Errorf("expected synthesized suffix and cch placeholder\n  want %q\n  got  %q", want, got)
	}
}

// TestSyncBillingHeaderVersion_EqualVersion verifies that even when the
// triple is unchanged, the 3hex is recomputed (the client's original
// suffix used vM3 with isMeta filter; ours uses the wire body, so values
// can differ even at "same version") and a cch placeholder is injected.
func TestSyncBillingHeaderVersion_EqualVersion(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.88.zzz; cc_entrypoint=cli;"}
		],
		"messages": [{"role":"user","content":"hi"}]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	wantSuffix := Compute3HexSuffix("2.1.88", []interface{}{
		map[string]interface{}{"role": "user", "content": "hi"},
	})
	want := "x-anthropic-billing-header: cc_version=2.1.88." + wantSuffix + "; cc_entrypoint=cli; cch=00000;"
	if got != want {
		t.Errorf("equal-version block:\n  want %q\n  got  %q", want, got)
	}
}

func TestSyncBillingHeaderVersion_StringSystem(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": "x-anthropic-billing-header: cc_version=2.1.76.df2; cc_entrypoint=cli;",
		"messages": [{"role":"user","content":"hi"}]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	got := parsed["system"].(string)
	wantSuffix := Compute3HexSuffix("2.1.88", []interface{}{
		map[string]interface{}{"role": "user", "content": "hi"},
	})
	want := "x-anthropic-billing-header: cc_version=2.1.88." + wantSuffix + "; cc_entrypoint=cli; cch=00000;"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestSyncBillingHeaderVersion_NonBillingStringIsUntouched(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": "You are Claude Code. cc_version=2.1.76 appears in user text."
	}`)
	original := parsed["system"].(string)

	syncBillingHeaderVersion(parsed, "2.1.88")

	got := parsed["system"].(string)
	if got != original {
		t.Errorf("non-billing string system was mutated: %q -> %q", original, got)
	}
}

func TestSyncBillingHeaderVersion_NoBillingBlock(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"You are Claude Code, Anthropic's official CLI for Claude."}
		]
	}`)

	before, _ := json.Marshal(parsed)
	syncBillingHeaderVersion(parsed, "2.1.88")
	after, _ := json.Marshal(parsed)

	if string(before) != string(after) {
		t.Errorf("expected no change, got before=%s after=%s", before, after)
	}
}

func TestSyncBillingHeaderVersion_NoSystemField(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{"messages":[]}`)

	before, _ := json.Marshal(parsed)
	syncBillingHeaderVersion(parsed, "2.1.88")
	after, _ := json.Marshal(parsed)

	if string(before) != string(after) {
		t.Errorf("expected no change, got before=%s after=%s", before, after)
	}
}

func TestSyncBillingHeaderVersion_EmptyUAVersion(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76.df2; cch=abc12"}
		]
	}`)
	before, _ := json.Marshal(parsed)

	syncBillingHeaderVersion(parsed, "")

	after, _ := json.Marshal(parsed)
	if string(before) != string(after) {
		t.Errorf("empty uaVersion must be a no-op, got before=%s after=%s", before, after)
	}
}

func TestSyncBillingHeaderVersion_NilParsed(t *testing.T) {
	t.Parallel()
	// Must not panic.
	syncBillingHeaderVersion(nil, "2.1.88")
}

// TestSyncBillingHeaderVersion_MultipleBlocksOnlyBillingMutated verifies that
// in a request mixing billing and non-billing system blocks (and a user-
// authored block that happens to contain "cc_version="), only the genuine
// billing blocks are touched.
func TestSyncBillingHeaderVersion_MultipleBlocksOnlyBillingMutated(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76.df2; cch=abc12"},
			{"type":"text","text":"cc_version=2.1.76 this is user-authored text"},
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.70.qqq; cc_entrypoint=cli;"}
		],
		"messages": [{"role":"user","content":"hi"}]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	wantSuffix := Compute3HexSuffix("2.1.88", []interface{}{
		map[string]interface{}{"role": "user", "content": "hi"},
	})

	got0 := sys[0].(map[string]interface{})["text"].(string)
	want0 := "x-anthropic-billing-header: cc_version=2.1.88." + wantSuffix + "; cch=00000"
	if got0 != want0 {
		t.Errorf("block 0 mismatch:\n  want %q\n  got  %q", want0, got0)
	}
	// block 1 is NOT a billing header — must be untouched even though it
	// contains "cc_version=2.1.76".
	got1 := sys[1].(map[string]interface{})["text"].(string)
	if got1 != "cc_version=2.1.76 this is user-authored text" {
		t.Errorf("non-billing block 1 was mutated: %q", got1)
	}
	got2 := sys[2].(map[string]interface{})["text"].(string)
	want2 := "x-anthropic-billing-header: cc_version=2.1.88." + wantSuffix + "; cc_entrypoint=cli; cch=00000;"
	if got2 != want2 {
		t.Errorf("block 2 mismatch:\n  want %q\n  got  %q", want2, got2)
	}
}

// parseJSON is a small helper for test body construction.
func parseJSON(t *testing.T, s string) map[string]interface{} {
	t.Helper()
	var m map[string]interface{}
	if err := json.Unmarshal([]byte(s), &m); err != nil {
		t.Fatalf("parseJSON: %v", err)
	}
	return m
}
