package disguise

import (
	"encoding/json"
	"testing"
)

// TestComputeBillingFingerprint_KnownVectors pins the SHA256-based fingerprint
// algorithm to byte-exact expected values. These vectors were generated by a
// standalone Go program using the documented algorithm:
//
//	SHA256("59cf53e54c78" + msg[4] + msg[7] + msg[20] + version)[:3]
//
// with out-of-range indices substituted with '0'. If upstream ever changes
// the salt, indices, or hash digest, these tests will fail loudly. Any
// change must be cross-checked against real Claude CLI traffic AND the
// auth2api reference (../auth2api/src/proxy/cloaking.ts:computeFingerprint).
func TestComputeBillingFingerprint_KnownVectors(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name    string
		msg     string
		version string
		want    string
	}{
		// msg shorter than max index (20) → all three chars are '0'.
		{"empty message 2.1.88", "", "2.1.88", "758"},
		{"empty message 2.1.76", "", "2.1.76", "4dc"},
		{"short message 2.1.88", "hi", "2.1.88", "758"},
		// Long enough to cover all three indices (4=o, 7=w, 20=t).
		{"long message 2.1.88", "Hello, world! This is a test message.", "2.1.88", "e72"},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := computeBillingFingerprint(tc.msg, tc.version)
			if got != tc.want {
				t.Errorf("computeBillingFingerprint(%q, %q) = %q, want %q",
					tc.msg, tc.version, got, tc.want)
			}
		})
	}
}

func TestExtractFirstUserMessageText(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		body string
		want string
	}{
		{
			name: "string content",
			body: `{"messages":[{"role":"user","content":"hello there"}]}`,
			want: "hello there",
		},
		{
			name: "array with text block",
			body: `{"messages":[{"role":"user","content":[{"type":"text","text":"block text"}]}]}`,
			want: "block text",
		},
		{
			name: "array with non-text block first",
			body: `{"messages":[{"role":"user","content":[{"type":"image"},{"type":"text","text":"t"}]}]}`,
			want: "t",
		},
		{
			name: "assistant before user",
			body: `{"messages":[{"role":"assistant","content":"ai"},{"role":"user","content":"human"}]}`,
			want: "human",
		},
		{
			name: "no user message",
			body: `{"messages":[{"role":"assistant","content":"ai"}]}`,
			want: "",
		},
		{
			name: "no messages field",
			body: `{}`,
			want: "",
		},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			parsed := parseJSON(t, tc.body)
			got := extractFirstUserMessageText(parsed)
			if got != tc.want {
				t.Errorf("extractFirstUserMessageText = %q, want %q", got, tc.want)
			}
		})
	}
}

// expectedSuffix is the fingerprint for an empty user message at version
// 2.1.88 — the value used by tests that don't supply messages.
const expectedSuffix2_1_88EmptyMsg = "758"

func TestSyncBillingHeaderVersion_ArraySystemRecomputesSuffix(t *testing.T) {
	t.Parallel()
	// Note: no "messages" field → extractFirstUserMessageText returns "" →
	// suffix computed from empty chars + version "2.1.88" = "758".
	// The OLD ".df2" suffix must be REPLACED, not preserved.
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76.df2; cc_entrypoint=cli; cch=abc12"},
			{"type":"text","text":"You are Claude Code."}
		],
		"messages":[]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	want := "x-anthropic-billing-header: cc_version=2.1.88." + expectedSuffix2_1_88EmptyMsg + "; cc_entrypoint=cli; cch=abc12"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
	// Non-billing block must be untouched.
	other := sys[1].(map[string]interface{})["text"].(string)
	if other != "You are Claude Code." {
		t.Errorf("non-billing block was mutated: %q", other)
	}
}

func TestSyncBillingHeaderVersion_NoSuffix_AppendsSuffix(t *testing.T) {
	t.Parallel()
	// Client sent a suffix-less cc_version. After sync, the suffix must be
	// appended so the output is always fully-qualified.
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76; cc_entrypoint=cli;"}
		]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	want := "x-anthropic-billing-header: cc_version=2.1.88." + expectedSuffix2_1_88EmptyMsg + "; cc_entrypoint=cli;"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestSyncBillingHeaderVersion_StringSystem(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": "x-anthropic-billing-header: cc_version=2.1.76.df2; cc_entrypoint=cli;"
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	got := parsed["system"].(string)
	want := "x-anthropic-billing-header: cc_version=2.1.88." + expectedSuffix2_1_88EmptyMsg + "; cc_entrypoint=cli;"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestSyncBillingHeaderVersion_NonBillingStringIsUntouched(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": "You are Claude Code. cc_version=2.1.76 appears in user text."
	}`)
	original := parsed["system"].(string)

	syncBillingHeaderVersion(parsed, "2.1.88")

	got := parsed["system"].(string)
	if got != original {
		t.Errorf("non-billing string system was mutated: %q -> %q", original, got)
	}
}

func TestSyncBillingHeaderVersion_NoBillingBlock(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"You are Claude Code, Anthropic's official CLI for Claude."}
		]
	}`)

	before, _ := json.Marshal(parsed)
	syncBillingHeaderVersion(parsed, "2.1.88")
	after, _ := json.Marshal(parsed)

	if string(before) != string(after) {
		t.Errorf("expected no change, got before=%s after=%s", before, after)
	}
}

func TestSyncBillingHeaderVersion_NoSystemField(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{"messages":[]}`)

	before, _ := json.Marshal(parsed)
	syncBillingHeaderVersion(parsed, "2.1.88")
	after, _ := json.Marshal(parsed)

	if string(before) != string(after) {
		t.Errorf("expected no change, got before=%s after=%s", before, after)
	}
}

func TestSyncBillingHeaderVersion_EmptyUAVersion(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76.df2; cch=abc12"}
		]
	}`)
	before, _ := json.Marshal(parsed)

	syncBillingHeaderVersion(parsed, "")

	after, _ := json.Marshal(parsed)
	if string(before) != string(after) {
		t.Errorf("empty uaVersion must be a no-op, got before=%s after=%s", before, after)
	}
}

func TestSyncBillingHeaderVersion_NilParsed(t *testing.T) {
	t.Parallel()
	// Must not panic.
	syncBillingHeaderVersion(nil, "2.1.88")
}

func TestSyncBillingHeaderVersion_MultipleBlocksOnlyBillingMutated(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76.df2; cch=abc12"},
			{"type":"text","text":"cc_version=2.1.76 this is user-authored text"},
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.70; cc_entrypoint=cli;"}
		]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got0 := sys[0].(map[string]interface{})["text"].(string)
	want0 := "x-anthropic-billing-header: cc_version=2.1.88." + expectedSuffix2_1_88EmptyMsg + "; cch=abc12"
	if got0 != want0 {
		t.Errorf("block 0 mismatch:\n  want %q\n  got  %q", want0, got0)
	}
	// block 1 is NOT a billing header — must be untouched even though it
	// contains "cc_version=2.1.76".
	got1 := sys[1].(map[string]interface{})["text"].(string)
	if got1 != "cc_version=2.1.76 this is user-authored text" {
		t.Errorf("non-billing block 1 was mutated: %q", got1)
	}
	got2 := sys[2].(map[string]interface{})["text"].(string)
	want2 := "x-anthropic-billing-header: cc_version=2.1.88." + expectedSuffix2_1_88EmptyMsg + "; cc_entrypoint=cli;"
	if got2 != want2 {
		t.Errorf("block 2 mismatch:\n  want %q\n  got  %q", want2, got2)
	}
}

// TestSyncBillingHeaderVersion_UsesFirstUserMessage verifies that the
// fingerprint suffix varies with the request's first user message content,
// proving we're running the real algorithm and not a static replacement.
func TestSyncBillingHeaderVersion_UsesFirstUserMessage(t *testing.T) {
	t.Parallel()
	// "Hello, world! This is a test message." at 2.1.88 → suffix "e72"
	// (pinned in TestComputeBillingFingerprint_KnownVectors).
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76.xxx; cch=abc12"}
		],
		"messages": [
			{"role":"user","content":"Hello, world! This is a test message."}
		]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	want := "x-anthropic-billing-header: cc_version=2.1.88.e72; cch=abc12"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

// TestSyncBillingHeaderVersion_ClientEqualVersionIsUntouched verifies that
// when the client's cc_version matches uaVersion, the block is passed
// through byte-for-byte — we trust the client's real-algorithm suffix
// rather than risk clobbering it with our replicated algorithm.
func TestSyncBillingHeaderVersion_ClientEqualVersionIsUntouched(t *testing.T) {
	t.Parallel()
	// Note the unusual suffix "zzz" — if our code rewrote the block we'd
	// overwrite this with the SHA256 result. Preserving it proves the
	// equal-version branch short-circuits.
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.88.zzz; cc_entrypoint=cli;"}
		],
		"messages": [{"role":"user","content":"anything"}]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	want := "x-anthropic-billing-header: cc_version=2.1.88.zzz; cc_entrypoint=cli;"
	if got != want {
		t.Errorf("equal-version block was mutated:\n  want %q\n  got  %q", want, got)
	}
}

// TestSyncBillingHeaderVersion_ClientNewerVersionIsUntouched verifies that
// a client running a newer CLI than our fp UA is trusted as-is. This can
// happen transiently when a new Claude CLI release ships and ccproxy's
// DefaultHeaders hasn't been bumped yet — better to pass through a mismatched
// UA-body tuple for a real rare case than to aggressively downgrade a valid
// client fingerprint using our stale algorithm.
func TestSyncBillingHeaderVersion_ClientNewerVersionIsUntouched(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.2.0.abc; cc_entrypoint=cli;"}
		],
		"messages": [{"role":"user","content":"anything"}]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	got := sys[0].(map[string]interface{})["text"].(string)
	want := "x-anthropic-billing-header: cc_version=2.2.0.abc; cc_entrypoint=cli;"
	if got != want {
		t.Errorf("newer-version block was mutated:\n  want %q\n  got  %q", want, got)
	}
}

// TestSyncBillingHeaderVersion_MixedBlockVersions verifies that in a request
// with multiple billing blocks, only the strictly-older ones are upgraded
// and the equal/newer ones are preserved.
func TestSyncBillingHeaderVersion_MixedBlockVersions(t *testing.T) {
	t.Parallel()
	parsed := parseJSON(t, `{
		"system": [
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.76.xxx; cch=old"},
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.1.88.zzz; cch=equal"},
			{"type":"text","text":"x-anthropic-billing-header: cc_version=2.2.0.abc; cch=newer"}
		]
	}`)

	syncBillingHeaderVersion(parsed, "2.1.88")

	sys := parsed["system"].([]interface{})
	// Block 0 upgraded from 2.1.76 to 2.1.88 with recomputed "758" suffix.
	got0 := sys[0].(map[string]interface{})["text"].(string)
	want0 := "x-anthropic-billing-header: cc_version=2.1.88." + expectedSuffix2_1_88EmptyMsg + "; cch=old"
	if got0 != want0 {
		t.Errorf("block 0 should be upgraded:\n  want %q\n  got  %q", want0, got0)
	}
	// Block 1 (equal version) untouched — "zzz" suffix preserved.
	got1 := sys[1].(map[string]interface{})["text"].(string)
	want1 := "x-anthropic-billing-header: cc_version=2.1.88.zzz; cch=equal"
	if got1 != want1 {
		t.Errorf("block 1 should be untouched:\n  want %q\n  got  %q", want1, got1)
	}
	// Block 2 (newer version) untouched — "abc" suffix preserved.
	got2 := sys[2].(map[string]interface{})["text"].(string)
	want2 := "x-anthropic-billing-header: cc_version=2.2.0.abc; cch=newer"
	if got2 != want2 {
		t.Errorf("block 2 should be untouched:\n  want %q\n  got  %q", want2, got2)
	}
}

// parseJSON is a small helper for test body construction.
func parseJSON(t *testing.T, s string) map[string]interface{} {
	t.Helper()
	var m map[string]interface{}
	if err := json.Unmarshal([]byte(s), &m); err != nil {
		t.Fatalf("parseJSON: %v", err)
	}
	return m
}
